[project]
name = "production-agentic-rag"
version = "0.1.0"
description = "Production ready Agentic RAG system"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "fastapi[standard]>=0.136.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "opensearch-py>=3.2.0",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.1",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "notebook>=7.5.6",
]
